---
deployment:
  tasks:
    # Set the deployment path to the public_html directory
    - export DEPLOYPATH=/home/phaedrrd/public_html
    # Copy all contents of the dist folder to the public_html directory
    - /bin/cp -R dist/* $DEPLOYPATH
